version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: memefactory
      POSTGRES_USER: memefactory
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memefactory"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    command: npm start

  stream-worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: npm run worker:stream

  poll-worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: npm run worker:poll

  scorer-worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: npm run worker:scorer
    deploy:
      replicas: 2

  launcher-worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: npm run worker:launcher

  treasury-worker:
    build: .
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://memefactory:changeme@postgres:5432/memefactory
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    command: npm run worker:treasury

volumes:
  postgres_data:
  redis_data:
